### ISSUE TITLE
Thread.exclusive is deprecated, use Mutex in InheritableClassInstanceVariables

### ISSUE THREAD

**Issue by liveh2o** [abrandoned/heredity#5]
It looks like Thread.exclusive is being deprecated in favor of a Mutex in Ruby:

```Ruby
Thread.exclusive is deprecated, use Mutex
/Users/ah/.rvm/gems/ruby-2.3.0@abacus/gems/heredity-0.1.1/lib/heredity/inheritable_class_instance_variables.rb:8:in `included'
/Users/ah/.rvm/gems/ruby-2.3.0@abacus/gems/heredity-0.1.1/lib/heredity.rb:9:in `include'
/Users/ah/.rvm/gems/ruby-2.3.0@abacus/gems/heredity-0.1.1/lib/heredity.rb:9:in `block in included'
/Users/ah/.rvm/gems/ruby-2.3.0@abacus/gems/heredity-0.1.1/lib/heredity.rb:8:in `class_eval'
/Users/ah/.rvm/gems/ruby-2.3.0@abacus/gems/heredity-0.1.1/lib/heredity.rb:8:in `included'
```

We should update Heredity to accommodate.

**Comment by lenage** [comment]
0.1.2 has been resolved this issue, see https://github.com/abrandoned/heredity/pull/7/files
